name : Java CI with Maven - Test and package
on: [pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'corretto'
            - name: Build with Maven
              env:
               SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              run: mvn -B verify sonar:sonar -Dsonar.projectKey=$(echo ${{ github.repository }} | sed 's-/-_-') -Dsonar.login=${{ secrets.SONAR_TOKEN }}

